In [71]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [72]:
df = pd.read_csv('cars.csv')
df.sample(10)

        brand  km_driven    fuel         owner  selling_price
7282   Maruti      53190  Diesel   First Owner         450000
4120  Hyundai      55000  Petrol  Second Owner         114999
3952  Renault      85000  Diesel   First Owner         315000
83     Maruti      10000  Petrol   First Owner         484999
3495   Maruti     108800  Diesel   Third Owner         450000
2832     Jeep      22000  Petrol   First Owner        1450000
7877  Hyundai      20000  Petrol   First Owner         990000
5467   Toyota     426000  Diesel   First Owner         950000
3795     Tata      90000  Diesel  Second Owner         350000
6026  Hyundai      90000  Diesel  Second Owner         459999

In [73]:
df[['owner']].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

### OneHotEncoding using Sklearn

In [74]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, :4], df.iloc[:, -1], test_size=0.2, random_state=10)

In [75]:
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)

In [76]:
x_train_new = ohe.fit_transform(x_train[['fuel', 'owner']])
x_test_new = ohe.transform(x_test[['fuel', 'owner']])

x_train_new.shape

(6502, 7)

In [ ]:
np.hstack((x_train[['brand', 'km_driven']].values, x_train_new))

array([['Toyota', 90000, 1, ..., 0, 0, 0],
       ['Hyundai', 60000, 0, ..., 1, 0, 0],
       ['Ford', 105000, 1, ..., 0, 0, 0],
       ...,
       ['Maruti', 70000, 1, ..., 1, 0, 0],
       ['Maruti', 57000, 1, ..., 0, 0, 0],
       ['Hyundai', 90000, 1, ..., 1, 0, 0]], shape=(6502, 9), dtype=object)

### OneHotEncoding with Top Categories

In [78]:
counts = df['brand'].value_counts()
# df['brand'].nunique()
threshold = 100
replace = counts[counts <= threshold].index
pd.get_dummies(df['brand'].replace(replace, 'uncommon'), dtype=np.int32).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
3285,0,0,0,0,0,1,0,0,0,0,0,0,0
1545,0,0,0,0,0,0,1,0,0,0,0,0,0
2111,0,0,0,0,1,0,0,0,0,0,0,0,0
4871,0,0,0,0,0,0,1,0,0,0,0,0,0
682,0,0,0,0,0,0,0,0,0,0,1,0,0