In [392]:
import numpy as np 
import pandas as pd 
from matplotlib import pyplot
import seaborn as sns

In [393]:
df = pd.read_csv('../data/Telco-Customer-Churn.csv')
df.sample(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
1832,3132-TVFDZ,Male,1,Yes,No,57,No,No phone service,DSL,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,44.85,2572.95,Yes
236,0621-JFHOL,Female,0,No,No,10,No,No phone service,DSL,No,...,No,Yes,No,No,Two year,Yes,Mailed check,29.60,299.05,No
1170,9127-FHJBZ,Male,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,114.00,8093.15,No
2539,2050-ONYDQ,Female,0,Yes,Yes,65,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),26.00,1654.85,No
926,7074-IEVOJ,Female,1,No,No,3,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,79.40,205.05,Yes

In [394]:
# df.info()

In [395]:
df['TotalCharges'] = df['TotalCharges'].replace(' ', np.nan)
df['TotalCharges'] = df['TotalCharges'].astype(float)

In [396]:
df[df['TotalCharges'].isna()][
    ['tenure', 'MonthlyCharges', 'TotalCharges', 'Churn']
]

      tenure  MonthlyCharges  TotalCharges Churn
488        0           52.55           NaN    No
753        0           20.25           NaN    No
936        0           80.85           NaN    No
1082       0           25.75           NaN    No
1340       0           56.05           NaN    No
3331       0           19.85           NaN    No
3826       0           25.35           NaN    No
4380       0           20.00           NaN    No
5218       0           19.70           NaN    No
6670       0           73.35           NaN    No
6754       0           61.90           NaN    No

In [397]:
df[df['TotalCharges'].isna()].T   # To check these customer are legit and there is no corrupted data

,488,753,936,1082,1340,3331,3826,4380,5218,6670,6754
customerID,4472-LVYGI,3115-CZMZD,5709-LVOEQ,4367-NUYAO,1371-DWPAZ,7644-OMVMY,3213-VVOLG,2520-SGTTA,2923-ARZLG,4075-WKNIU,2775-SEFEE
gender,Female,Male,Female,Male,Female,Male,Male,Female,Male,Female,Male
SeniorCitizen,0,0,0,0,0,0,0,0,0,0,0
Partner,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,No
Dependents,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes
tenure,0,0,0,0,0,0,0,0,0,0,0
PhoneService,No,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes
MultipleLines,No phone service,No,No,Yes,No phone service,No,Yes,No,No,Yes,Yes
InternetService,DSL,No,DSL,No,DSL,No,No,No,No,DSL,DSL
OnlineSecurity,Yes,No internet service,Yes,No internet service,Yes,No internet service,No internet service,No internet service,No internet service,No,Yes
OnlineBackup,No,No internet service,Yes,No internet service,Yes,No internet service,No internet service,No internet service,No internet service,Yes,Yes
DeviceProtection,Yes,No internet service,Yes,No internet service,Yes,No internet service,No internet service,No internet service,No internet service,Yes,No
TechSupport,Yes,No internet service,No,No internet service,Yes,No internet service,No internet service,No internet service,No internet service,Yes,Yes
StreamingTV,Yes,No internet service,Yes,No internet service,Yes,No internet service,No internet service,No internet service,No internet service,Yes,No
StreamingMovies,No,No internet service,Yes,No internet service,No,No internet service,No internet service,No internet service,No internet service,No,No
Contract,Two year,Two year,Two year,Two year,Two year,Two year,Two year,Two year,One year,Two year,Two year
PaperlessBilling,Yes,No,No,No,No,No,No,No,Yes,No,Yes
PaymentMethod,Bank transfer (automatic),Mailed check,Mailed check,Mailed check,Credit card (automatic),Mailed check,Mailed check,Mailed check,Mailed check,Mailed check,Bank transfer (automatic)
MonthlyCharges,52.55,20.25,80.85,25.75,56.05,19.85,25.35,20.0,19.7,73.35,61.9
TotalCharges,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Churn,No,No,No,No,No,No,No,No,No,No,No

In [398]:
df['TotalCharges'].isna().sum()

np.int64(11)

### Handling missing TotalCharges:
11 records had missing TotalCharges. Investigation showed that all 11 customers had tenure = 0, indicating that they were new customers. Since TotalCharges represents accumulated charges, these missing values were replaced with 0 rather than using statistical imputation

In [399]:
df['TotalCharges'] = df['TotalCharges'].fillna(0)  
df['TotalCharges'].isna().sum()

np.int64(0)

### Remvoing "customerID" because this will not effect the output of the final model

In [400]:
df = df.iloc[:, 1:]
df.shape

(7043, 20)

### Separate features (X) and target (y)

In [401]:
X = df.iloc[:, :-1]
Y = df.iloc[:, -1]

# X.shape 
Y.shape

(7043,)

### Changing Y values from str (Yes/No) to num (1/0) since logistic reg takes numerical values as input

In [402]:
Y = Y.map({'Yes' : 1, 'No' : 0})
Y.value_counts()

Churn
0    5174
1    1869
Name: count, dtype: int64

### Splitting the data into training and test

In [403]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=2, stratify=Y)

In [404]:
# y_train.value_counts(normalize=True)
# y_test.value_counts(normalize=True)

In [405]:
x_train.dtypes

gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges        float64
dtype: object

In [406]:
numeric_features = x_train.select_dtypes(
    include=['int64', 'float64']
).columns

categorical_features = x_train.select_dtypes(
    include=['object', 'str']
).columns

# print("Numerical:", list(numeric_features))
print("Categorical:", list(categorical_features))

Categorical: ['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

### Building a preprocessing pipeline

In [407]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

For numerical columns → standardize 
For categorical columns → one-hot encode

In [408]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ]
)

In [409]:
x_train_encoded = preprocessor.fit_transform(x_train)
x_test_encoded = preprocessor.transform(x_test)

In [410]:
x_train_encoded.shape

(5634, 45)

In [411]:
x_test_encoded.shape

(1409, 45)

### Training the Model

In [412]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

model = Pipeline([
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000))
])

In [413]:
model.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='str'))])),
                ('classifier', LogisticRegression(max_iter=1000))])

In [414]:
y_pred = model.predict(x_test)

In [415]:
model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='str'))])),
                ('classifier', LogisticRegression(max_iter=1000))])

In [416]:
y_pred[:20]

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])